import { Format, Rich_Text_Text } from '../../../../../../types/Rich_Text'
import { get_language_aspect } from './~utilities'
import { readFileSync } from 'fs'

const get_data_uri = (svg_string: string) => {
  const uri = `data:image/svg+xml;charset=utf-8;base64,${Buffer.from(svg_string).toString('base64')}`

  return uri
}

const text = (text: string, ...formats: Format[]): Rich_Text_Text => ({
  type: 'text',
  text,
  formats,
})

const link = (text: string, ...formats: Format[]): Rich_Text_Text => ({
  type: 'text',
  text,
  formats,
})

export const cantonese_tones = get_language_aspect({
  title: 'Tones & Sounds',
  description: 'Cantonese pronunciation basics.',
  content: [
    {
      type: 'paragraph',
      content: [
        text(
          'Cantonese is a tonal language. This means that literal meaning is not only conveyed through vowels and consonants - generated by the shape or position of the mouth and tongue - but also through ',
        ),
        text('changes in the pitch', 'bold'),
        text(" of the speaker's voice."),
      ],
    },
    {
      type: 'paragraph',
      content: [
        text(
          'This is fundamentally different from western languages, which only use pitch to communicate emotion and to enrich speech with information beyond the literal meaning of what is being said. This does not mean tonal languages lack this enrichtment, though, and Cantonese uses modal ending words in addition to volume and starting pitch to convey additional meaning.',
        ),
      ],
    },
    {
      type: 'paragraph',
      content: [
        text(
          "It's important to note that pitch in tonal languages isn't absolute. It's all about the ",
        ),
        text('relationships between pitches', 'bold'),
        text(
          " in what's spoken. Speaking a tonal language sounds and feels exactly like any other language.",
        ),
      ],
    },
    {
      type: 'heading',
      level: 2,
      content: [text('Tones')],
    },
    {
      type: 'paragraph',
      content: [text('Modern Cantonese distinguishes between six tones.')],
    },
    {
      type: 'list',
      list_type: 'ordered',
      items: [
        {
          content: [text('High, constant pitch')],
        },
        {
          content: [text('Strong rising, low to high pitch')],
        },

        {
          content: [text('Medium, constant pitch')],
        },
        {
          content: [text('Low falling, falling from low pitch')],
        },
        {
          content: [text('Medium rising, low to medium pitch')],
        },
        {
          content: [text('Low, constant pitch')],
        },
      ],
    },
    {
      type: 'image',
      url: get_data_uri(
        readFileSync(
          // @ts-expect-error
          import.meta.resolve('./cantonese_tones_simplified.svg').substring(7),
        ).toString(),
      ),
      alt_text: 'A graph with lines of different colors and corresponding tone numbers',
      caption: 'Simplified visualization of Cantonese tones.',
      height: 250,
      width: 250,
    },
    {
      type: 'image',
      url: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Cantonese_tones.svg',
      alt_text:
        'A graph with lines of different colors, and corresponding tone numbers and Chinese characters',
      caption: 'The measured relative pitch of words spoken by a native speaker.',
      height: 400,
      width: 400,
    },

    // https://commons.wikimedia.org/wiki/File:Zh-yue-%E4%BD%A0%E5%A5%BD.opus
    // https://commons.wikimedia.org/wiki/File:Zh-yue-%E8%A9%A9%E5%8F%B2%E8%A9%A6%E6%99%82%E5%B8%82%E4%BA%8B.opus
    // https://commons.wikimedia.org/wiki/File:LL-Q9186-Luilui6666-%E6%89%80%E4%BB%A5.wav
  ],
})
