name: continuous integration
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v3
        # https://github.com/actions/setup-node
        with:
          node-version: '18.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: lint
        run: pnpm run --recursive lint

  api:
    name: build & deploy api
    runs-on: ubuntu-latest
    needs: []
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGANISATION_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # https://github.com/actions/checkout
        with:
          submodules: true

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v3
        # https://github.com/actions/setup-node
        with:
          node-version: '18.x'
          cache: pnpm

      - name: install dependencies
        run: |
          pnpm install --dir packages/search --frozen-lockfile
          pnpm install --dir packages/api --frozen-lockfile

      - name: get search data
        run: pnpm run --dir packages/search get-data

      - name: build search
        run: pnpm run --dir packages/search build

      - name: build api
        run: pnpm run --dir packages/api build:vercel

      - name: deploy api
        run: pnpm --dir packages/api deploy:vercel --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        if: ${{ github.ref == 'refs/heads/default' }}

  app:
    name: build & deploy app
    runs-on: ubuntu-latest
    needs: []
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGANISATION_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_APP_PROJECT_ID }}
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v3
        # https://github.com/actions/setup-node
        with:
          node-version: '18.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --dir packages/app --frozen-lockfile

      - name: build app
        run: pnpm run --dir packages/app build

      - name: deploy app
        run: pnpm --dir packages/app deploy:vercel --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        if: ${{ github.ref == 'refs/heads/default' }}
