name: continuous integration
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: checkout
        uses: actions/checkout@v3
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v3
        # https://github.com/actions/setup-node
        with:
          node-version: "18.x"
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: lint
        run: pnpm run --recursive lint

  build_api:
    name: build api
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: checkout
        uses: actions/checkout@v3
        # https://github.com/actions/checkout
        with:
          submodules: true

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v3
        # https://github.com/actions/setup-node
        with:
          node-version: "18.x"
          cache: pnpm

      - name: install dependencies
        run: |
          pnpm install --dir packages/search --frozen-lockfile
          pnpm install --dir packages/api --frozen-lockfile

      - name: build search
        run: pnpm run --dir packages/search build

      - name: build api
        run: pnpm run --dir packages/api build:vercel

  build_app:
    name: build app
    runs-on: ubuntu-latest
    needs: []
    env:
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@v3
        # https://github.com/actions/setup-node
        with:
          node-version: "18.x"
          cache: pnpm

      - name: install dependencies
        run: pnpm install --dir packages/app --frozen-lockfile

      - name: build app
        run: pnpm run --dir packages/app build
