name: continuous integration
on: push
jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    needs: []
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        # https://github.com/actions/setup-node
        with:
          node-version: '22.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: lint
        run: pnpm audit --prod

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        # https://github.com/actions/setup-node
        with:
          node-version: '22.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: lint
        run: pnpm run --recursive lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        # https://github.com/actions/setup-node
        with:
          node-version: '22.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: test
        run: pnpm run --recursive test

  api:
    name: build & deploy api
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGANISATION_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # https://github.com/actions/checkout
        with:
          submodules: true

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        # https://github.com/actions/setup-node
        with:
          node-version: '22.x'
          cache: pnpm

      - name: install dependencies
        run: |
          pnpm install --dir search --frozen-lockfile
          pnpm install --dir api --frozen-lockfile

      - name: get search data
        run: pnpm run --dir search get-data

      - name: build search
        run: pnpm run --dir search build

      - name: build api
        run: pnpm run --dir api build:vercel

      - name: deploy api
        run: pnpm --dir api deploy:vercel --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        if: ${{ github.ref == 'refs/heads/default' }}

  app:
    name: build & deploy app
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGANISATION_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_APP_PROJECT_ID }}
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
      ISR_BYPASS_TOKEN: ${{ vars.ISR_BYPASS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@v2
        # https://github.com/pnpm/action-setup
        with:
          version: latest

      - name: set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        # https://github.com/actions/setup-node
        with:
          node-version: '22.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --dir app --frozen-lockfile

      - name: build app
        run: USE_VERCEL_ADAPTER=true pnpm run --dir app build

      - name: deploy app
        run: pnpm --dir app deploy:vercel --prod --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        if: ${{ github.ref == 'refs/heads/default' }}
