name: continuous integration
on: push
jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest
    needs: []
    continue-on-error: true
    if: github.ref == 'refs/heads/default'
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        # https://github.com/pnpm/action-setup
        with:
          version: 10.31.0

      - name: set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        # https://github.com/actions/setup-node
        with:
          node-version: '24.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: audit
        run: pnpm audit --prod

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: []
    env:
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
      PUBLIC_CANONICAL_BASE_URL: ${{ vars.PUBLIC_CANONICAL_BASE_URL }}
      STORYBLOK_ACCESS_TOKEN: ${{ secrets.STORYBLOK_ACCESS_TOKEN }}
      REMOTE_DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}
      REMOTE_DATABASE_AUTH_TOKEN: ${{ secrets.REMOTE_DATABASE_AUTH_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        # https://github.com/pnpm/action-setup
        with:
          version: 10.31.0

      - name: set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        # https://github.com/actions/setup-node
        with:
          node-version: '24.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: lint
        run: pnpm run --recursive lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: []
    env:
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
      PUBLIC_CANONICAL_BASE_URL: ${{ vars.PUBLIC_CANONICAL_BASE_URL }}
      STORYBLOK_ACCESS_TOKEN: ${{ secrets.STORYBLOK_ACCESS_TOKEN }}
      REMOTE_DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}
      REMOTE_DATABASE_AUTH_TOKEN: ${{ secrets.REMOTE_DATABASE_AUTH_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        # https://github.com/pnpm/action-setup
        with:
          version: 10.31.0

      - name: set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        # https://github.com/actions/setup-node
        with:
          node-version: '24.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: test
        run: pnpm run --recursive test

  app:
    name: build & deploy app
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORGANISATION_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_APP_PROJECT_ID }}
      VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
      PUBLIC_CANONICAL_BASE_URL: ${{ vars.PUBLIC_CANONICAL_BASE_URL }}
      ISR_BYPASS_TOKEN: ${{ secrets.ISR_BYPASS_TOKEN }}
      STORYBLOK_ACCESS_TOKEN: ${{ secrets.STORYBLOK_ACCESS_TOKEN }}
      REMOTE_DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}
      REMOTE_DATABASE_AUTH_TOKEN: ${{ secrets.REMOTE_DATABASE_AUTH_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # https://github.com/actions/checkout

      - name: set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        # https://github.com/pnpm/action-setup
        with:
          version: 10.31.0

      - name: set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        # https://github.com/actions/setup-node
        with:
          node-version: '24.x'
          cache: pnpm

      - name: install dependencies
        run: pnpm install --dir app --frozen-lockfile

      - name: build app
        run: pnpm run --dir app build

      - name: deploy app
        run: pnpm --dir app deploy:vercel --prod --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        if: ${{ github.ref == 'refs/heads/default' }}

      - name: deploy app preview
        run: pnpm --dir app deploy:vercel --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        if: ${{ github.ref != 'refs/heads/default' }}
